### ISSUE TITLE
Increase tla-account character upper limit to >=65?

### ISSUE THREAD

**Issue by shariffdev** [near/near-account-id-rs#18]
# Issue
The [stabilization of nep492](https://github.com/near/nearcore/pull/9658) made it only that the `"registrar"` can create accounts with characters <65. The account-id limit is set at 64. https://github.com/near/near-account-id-rs/blob/fafb6ef545aa0a35e06677cce550baac4d23cd19/src/validation.rs#L6

 This is a little urgent as `sandbox @1.36.0` with workspaces fail. The simple fix would be to change the configuration like so: https://github.com/shariffdev/nearcore/commit/fba184790fab198a42fee06482b45ff66f709dd4. We could make an exception and go for this although there's a [comment](https://github.com/near/nearcore/pull/9693#discussion_r1361605220) against it on my first try which is still relevant.

> This is also a departure from how sandbox functionality changes have been implemented in the past, which is feature gating specific areas of the implementation, rather than configuration.

Also if we tweak the config it will be a gotcha for devs after using workspaces.

# Possible solution
Come up with a set of different character limits. Perhaps, split the generalization and have `implicit accounts` remain at 64 while `top-level accounts` can be at >=65. This route would affect [near-sdk-rs](https://github.com/near/near-sdk-rs/blob/24f912743371a1b4655fea8aea490a18f319f15d/near-sdk/src/environment/env.rs#L36) and (maybe) other places... 

Or brainstorm a better/cleaner strategy.

Cc @frol @ChaoticTempest

**Comment by frol** [comment]
> while top-level accounts can be at >=65.

Since the account-id length requirement has not changed, that update in the config to >=65 effectively means that no top-level is allowed to be created without a registrar.

There are no actions needed to be taken in near-account-id.

near-workspaces-rs has to stop relying on top-level accounts and use subaccounts by default (just like most of the account on NEAR mainnet are subaccounts of `near` account, and on testnet - `testnet` is the top-level account)
